// Command generate-probes converts nmap-service-probes to a Go source file
// containing serialized probe data that can be loaded at runtime without
// distributing the original NPSL-licensed file.
//
// Usage:
//
//	go run ./cmd/generate-probes/ -input /path/to/nmap-service-probes -o probes_generated.go
package main

import (
	"encoding/json"
	"flag"
	"fmt"
	"log"
	"os"
	"time"

	"github.com/taigrr/gomap/probedb"
)

// serializedProbe is the JSON-friendly representation of a probe.
type serializedProbe struct {
	Name         string            `json:"name"`
	Protocol     string            `json:"protocol"`
	ProbeString  string            `json:"probe_string"` // hex-encoded
	Rarity       int               `json:"rarity"`
	Ports        string            `json:"ports"`
	SSLPorts     string            `json:"ssl_ports,omitempty"`
	TotalWaitMS  int               `json:"total_wait_ms"`
	TCPWrappedMS int               `json:"tcp_wrapped_ms,omitempty"`
	Fallback     string            `json:"fallback,omitempty"`
	Matches      []serializedMatch `json:"matches,omitempty"`
	SoftMatches  []serializedMatch `json:"soft_matches,omitempty"`
}

type serializedMatch struct {
	Service     string   `json:"service"`
	Pattern     string   `json:"pattern"`
	Flags       string   `json:"flags,omitempty"`
	ProductName string   `json:"product,omitempty"`
	Version     string   `json:"version,omitempty"`
	Info        string   `json:"info,omitempty"`
	Hostname    string   `json:"hostname,omitempty"`
	OS          string   `json:"os,omitempty"`
	DeviceType  string   `json:"device,omitempty"`
	CPE         []string `json:"cpe,omitempty"`
}

func main() {
	input := flag.String("input", "", "Path to nmap-service-probes file")
	output := flag.String("o", "probes_generated.go", "Output file path")
	flag.Parse()

	if *input == "" {
		log.Fatal("--input is required (path to nmap-service-probes)")
	}

	f, err := os.Open(*input)
	if err != nil {
		log.Fatalf("opening input: %v", err)
	}
	defer f.Close()

	db, err := probedb.ParseServiceProbes(f)
	if err != nil {
		log.Fatalf("parsing probes: %v", err)
	}

	log.Printf("Parsed %d probes", len(db.Probes))

	// Serialize probes to JSON, only keeping matches that compiled successfully
	var probes []serializedProbe
	totalMatches := 0
	skippedMatches := 0

	for _, p := range db.Probes {
		sp := serializedProbe{
			Name:         p.Name,
			Protocol:     p.Protocol,
			ProbeString:  fmt.Sprintf("%x", p.ProbeString),
			Rarity:       p.Rarity,
			Ports:        portSetToSpec(p.Ports),
			SSLPorts:     portSetToSpec(p.SSLPorts),
			TotalWaitMS:  p.TotalWaitMS,
			TCPWrappedMS: p.TCPWrappedMS,
			Fallback:     p.Fallback,
		}

		for _, m := range p.Matches {
			totalMatches++
			if m.Pattern == nil {
				skippedMatches++
				continue
			}
			sp.Matches = append(sp.Matches, serializeMatch(m))
		}
		for _, m := range p.SoftMatches {
			totalMatches++
			if m.Pattern == nil {
				skippedMatches++
				continue
			}
			sp.SoftMatches = append(sp.SoftMatches, serializeMatch(m))
		}

		probes = append(probes, sp)
	}

	log.Printf("Kept %d/%d matches (%d skipped due to incompatible regex)",
		totalMatches-skippedMatches, totalMatches, skippedMatches)

	// Serialize to JSON
	jsonData, err := json.Marshal(probes)
	if err != nil {
		log.Fatalf("marshaling JSON: %v", err)
	}

	// Write Go source file
	out, err := os.Create(*output)
	if err != nil {
		log.Fatalf("creating output: %v", err)
	}
	defer out.Close()

	fmt.Fprintf(out, "// Code generated by generate-probes; DO NOT EDIT.\n")
	fmt.Fprintf(out, "// Source: nmap-service-probes\n")
	fmt.Fprintf(out, "// Generated: %s\n", time.Now().UTC().Format(time.RFC3339))
	fmt.Fprintf(out, "// Probes: %d, Matches: %d\n\n", len(probes), totalMatches-skippedMatches)
	fmt.Fprintf(out, "package gomap\n\n")
	fmt.Fprintf(out, "// embeddedServiceProbesJSON contains the serialized service probe database.\n")
	fmt.Fprintf(out, "// It is parsed at init time into the default probe database.\n")
	fmt.Fprintf(out, "var embeddedServiceProbesJSON = %q\n", string(jsonData))

	log.Printf("Generated %s (%d bytes of JSON)", *output, len(jsonData))
}

func serializeMatch(m probedb.ServiceMatch) serializedMatch {
	sm := serializedMatch{
		Service: m.Service,
		Pattern: m.PatternStr,
		Flags:   m.Flags,
	}
	if m.VersionInfo.ProductName != "" {
		sm.ProductName = m.VersionInfo.ProductName
	}
	if m.VersionInfo.Version != "" {
		sm.Version = m.VersionInfo.Version
	}
	if m.VersionInfo.Info != "" {
		sm.Info = m.VersionInfo.Info
	}
	if m.VersionInfo.Hostname != "" {
		sm.Hostname = m.VersionInfo.Hostname
	}
	if m.VersionInfo.OS != "" {
		sm.OS = m.VersionInfo.OS
	}
	if m.VersionInfo.DeviceType != "" {
		sm.DeviceType = m.VersionInfo.DeviceType
	}
	if len(m.VersionInfo.CPE) > 0 {
		sm.CPE = m.VersionInfo.CPE
	}
	return sm
}

// portSetToSpec converts a PortSet back to a port specification string.
// This is a best-effort reconstruction; the original spec isn't preserved.
func portSetToSpec(ps probedb.PortSet) string {
	if ps.Len() == 0 {
		return ""
	}

	// Get sorted ports
	ports := ps.Sorted()
	if len(ports) == 0 {
		return ""
	}

	// Compress into ranges
	var parts []string
	start := ports[0]
	end := ports[0]

	for i := 1; i < len(ports); i++ {
		if ports[i] == end+1 {
			end = ports[i]
		} else {
			if start == end {
				parts = append(parts, fmt.Sprintf("%d", start))
			} else {
				parts = append(parts, fmt.Sprintf("%d-%d", start, end))
			}
			start = ports[i]
			end = ports[i]
		}
	}
	if start == end {
		parts = append(parts, fmt.Sprintf("%d", start))
	} else {
		parts = append(parts, fmt.Sprintf("%d-%d", start, end))
	}

	result := ""
	for i, p := range parts {
		if i > 0 {
			result += ","
		}
		result += p
	}
	return result
}
