// Command generate-mac converts nmap-mac-prefixes to a Go source file.
//
// Usage:
//
//	go run ./cmd/generate-mac/ -input /path/to/nmap-mac-prefixes -o mac_generated.go
package main

import (
	"bufio"
	"flag"
	"fmt"
	"log"
	"os"
	"strings"
	"time"
)

func main() {
	input := flag.String("input", "", "Path to nmap-mac-prefixes file")
	output := flag.String("o", "mac_generated.go", "Output file path")
	flag.Parse()

	if *input == "" {
		log.Fatal("--input is required (path to nmap-mac-prefixes)")
	}

	f, err := os.Open(*input)
	if err != nil {
		log.Fatalf("opening input: %v", err)
	}
	defer f.Close()

	type entry struct {
		prefix string
		vendor string
	}
	var entries []entry
	seen := make(map[string]bool)

	scanner := bufio.NewScanner(f)
	for scanner.Scan() {
		line := scanner.Text()
		if strings.HasPrefix(line, "#") || line == "" {
			continue
		}
		if len(line) < 7 {
			continue
		}
		prefix := strings.ToUpper(line[:6])
		vendor := strings.TrimSpace(line[6:])
		if vendor == "" || seen[prefix] {
			continue
		}
		seen[prefix] = true
		entries = append(entries, entry{prefix, vendor})
	}
	if err := scanner.Err(); err != nil {
		log.Fatalf("reading input: %v", err)
	}

	log.Printf("Parsed %d MAC prefixes", len(entries))

	out, err := os.Create(*output)
	if err != nil {
		log.Fatalf("creating output: %v", err)
	}
	defer out.Close()

	fmt.Fprintf(out, "// Code generated by generate-mac; DO NOT EDIT.\n")
	fmt.Fprintf(out, "// Source: nmap-mac-prefixes (IEEE OUI database)\n")
	fmt.Fprintf(out, "// Generated: %s\n\n", time.Now().UTC().Format(time.RFC3339))
	fmt.Fprintf(out, "package gomap\n\n")
	fmt.Fprintf(out, "// MACPrefixes maps 6-character uppercase hex OUI prefixes to vendor names.\n")
	fmt.Fprintf(out, "// Contains %d entries.\n", len(entries))
	fmt.Fprintf(out, "var MACPrefixes = map[string]string{\n")

	for _, e := range entries {
		fmt.Fprintf(out, "\t%q: %q,\n", strings.ToUpper(e.prefix), e.vendor)
	}

	fmt.Fprintf(out, "}\n")

	log.Printf("Generated %s", *output)
}
