// Command generate-services fetches the IANA service names registry and
// generates a Go source file with port-to-service mappings.
//
//go:generate go run . -o ../../services_generated.go
package main

import (
	"encoding/csv"
	"flag"
	"fmt"
	"io"
	"log"
	"net/http"
	"os"
	"sort"
	"strconv"
	"strings"
	"text/template"
	"time"
)

const ianaURL = "https://www.iana.org/assignments/service-names-port-numbers/service-names-port-numbers.csv"

type service struct {
	Name        string
	Port        int
	Protocol    string
	Description string
}

func main() {
	output := flag.String("o", "services_generated.go", "Output file path")
	flag.Parse()

	log.Printf("Fetching IANA service registry from %s", ianaURL)
	resp, err := http.Get(ianaURL)
	if err != nil {
		log.Fatalf("fetching IANA data: %v", err)
	}
	defer resp.Body.Close()

	reader := csv.NewReader(resp.Body)
	reader.LazyQuotes = true

	// Skip header
	if _, err := reader.Read(); err != nil {
		log.Fatalf("reading header: %v", err)
	}

	// Parse: tcp services keyed by port, prefer named services
	tcpServices := make(map[int]service)
	udpServices := make(map[int]service)

	for {
		record, err := reader.Read()
		if err == io.EOF {
			break
		}
		if err != nil {
			continue
		}

		name := record[0]
		portStr := record[1]
		proto := record[2]
		desc := record[3]

		if name == "" || portStr == "" || proto == "" {
			continue
		}

		// Handle port ranges (e.g., "49152-65535")
		if strings.Contains(portStr, "-") {
			continue // skip ranges
		}

		port, err := strconv.Atoi(portStr)
		if err != nil {
			continue
		}

		// Use description if available, otherwise service name
		displayName := desc
		if displayName == "" {
			displayName = name
		}

		svc := service{
			Name:        name,
			Port:        port,
			Protocol:    proto,
			Description: displayName,
		}

		switch proto {
		case "tcp":
			if _, exists := tcpServices[port]; !exists {
				tcpServices[port] = svc
			}
		case "udp":
			if _, exists := udpServices[port]; !exists {
				udpServices[port] = svc
			}
		}
	}

	// Sort by port
	tcpPorts := sortedKeys(tcpServices)
	udpPorts := sortedKeys(udpServices)

	log.Printf("Parsed %d TCP services, %d UDP services", len(tcpPorts), len(udpPorts))

	// Generate Go file
	data := templateData{
		Generated: time.Now().UTC().Format(time.RFC3339),
		TCP:       make([]entry, 0, len(tcpPorts)),
		UDP:       make([]entry, 0, len(udpPorts)),
	}

	for _, port := range tcpPorts {
		svc := tcpServices[port]
		data.TCP = append(data.TCP, entry{Port: port, Name: svc.Name, Desc: svc.Description})
	}
	for _, port := range udpPorts {
		svc := udpServices[port]
		data.UDP = append(data.UDP, entry{Port: port, Name: svc.Name, Desc: svc.Description})
	}

	f, err := os.Create(*output)
	if err != nil {
		log.Fatalf("creating output file: %v", err)
	}
	defer f.Close()

	if err := tmpl.Execute(f, data); err != nil {
		log.Fatalf("executing template: %v", err)
	}

	log.Printf("Generated %s", *output)
}

func sortedKeys(m map[int]service) []int {
	keys := make([]int, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	sort.Ints(keys)
	return keys
}

type templateData struct {
	Generated string
	TCP       []entry
	UDP       []entry
}

type entry struct {
	Port int
	Name string
	Desc string
}

var tmpl = template.Must(template.New("services").Parse(`// Code generated by generate-services; DO NOT EDIT.
// Source: IANA Service Name and Transport Protocol Port Number Registry
// Generated: {{ .Generated }}

package gomap

// IANATCPServices maps TCP port numbers to IANA-registered service names.
var IANATCPServices = map[int]string{
{{- range .TCP }}
	{{ .Port }}: {{ printf "%q" .Desc }},
{{- end }}
}

// IANAUDPServices maps UDP port numbers to IANA-registered service names.
var IANAUDPServices = map[int]string{
{{- range .UDP }}
	{{ .Port }}: {{ printf "%q" .Desc }},
{{- end }}
}
`))

func init() {
	// Silence unused import warnings during generation
	_ = fmt.Sprint
}
